name: AangsLegacy
version: '${version}'

main: net.kylanic.aangslegacy.AangsLegacy
api-version: '26.2'
load: POSTWORLD

authors: [ Vexor, Kylanic Studios ]

commands:
  who:
    description: Shows the bender information about a player
    usage: /who <player>